### ISSUE TITLE
Toevoegen Licentie

### ISSUE THREAD

**Issue by lesander** [metiscoderclass/metiscoderclass.github.io#1]
Om duidelijk te maken dat de documentatie en code van [Handleiding GitHub Pages](https://piersoncollege.github.io/html) [1] gratis en voor niets gedeeld en bewerkt mag worden, is er een [licentie](https://github.com/Piersoncollege/html/blob/master/LICENSE) [2] toegevoegd aan de [repository](https://github.com/Piersoncollege/html) [3] van het Ds. Pierson College. Met een open-source MIT Licentie & Creative Commons Licentie moet dit duidelijk worden gemaakt.

Per de MIT Licentie en CC-BY-NC-SA 4.0 moet deze licentie overgenomen worden in de [repository van metiscoderclass](https://github.com/metiscoderclass/metiscoderclass.github.io/tree/master/publiceer-webpagina-github) [4] in bijvoorbeeld het bestand `LICENSE-HANDLEIDING-GITHUB-PAGES` en een link in de footer van de handleiding op de [website](https://metiscoderclass.github.io/publiceer-webpagina-github/) [5].

[1] https://piersoncollege.github.io/html
[2] https://github.com/Piersoncollege/html/blob/master/LICENSE
[3] https://github.com/Piersoncollege/html
[4] https://github.com/metiscoderclass/metiscoderclass.github.io/tree/master/publiceer-webpagina-github
[5] https://metiscoderclass.github.io/publiceer-webpagina-github/

**Comment by jurjenhickmann** [comment]
Dank voor het commentaar.

Ik heb het aangepast.
